branches: 
  - main
debug: false
tagFormat: v${version}
verifyConditions: "@semantic-release/github"
analyzeCommits: "@semantic-release/commit-analyzer"
generateNotes: "@semantic-release/release-notes-generator"
plugins:
- "@semantic-release/git"
prepare: 
- path: "@semantic-release/git"
  message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  assets: 
  - sps-api-standards.spectral.yml
publish: 
- path: "@semantic-release/github"
  assets:
  - path: sps-api-standards-documentation.zip
    label: sps-api-standards-documentation.zip
  - path: sps-api-standards.spectral.yml
    label: sps-api-standards.spectral.yml
  - path: LICENSE.txt
    label: LICENSE.txt
dryRun: false
ci: true
success: false
fail: false