remote_theme: carlosperate/jekyll-theme-rtd
title: SPS REST API Standards
site_author: SPS Commerce
repo_url: 'https://github.com/spscommerce/sps-api-standards'
edit_on_github: true
github_docs_folder: false
logo: 'https://www.spscommerce.com/wp-content/uploads/2017/09/logo-with-tag1.png'
site_favicon: 'https://www.spscommerce.com/favicon.ico'
prev_next_buttons_location: bottom
sticky_navigation: true
search_enabled: true
hljs_style: github-gist
