trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - standards/*
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: spscommerce/azure-pipelines-templates
      endpoint: vsts-infrastructure-sps-shared

extends:
  template: core/bdp.base.v1.yml@templates
  parameters:
    bdpFile: .bdp
    stages:
    - stage: VERSION
      jobs:

      - job: BUILD
        pool: BUILD-LINUX
        steps:
        - checkout: self
          clean: true

        - task: SemanticRelease@1
          displayName: 'semantic versioning'
          condition: and(succeeded(), eq(variables.isDefault, true))
          inputs: 
            tagFormat: v${version}
            failOnNoVersion: true

        - task: CopyFiles@2
          displayName: 'copy version of the files'
          inputs:
            contents: |
              standards/**
            targetFolder: $(Build.ArtifactStagingDirectory)

        - publish: $(Build.ArtifactStagingDirectory)
          displayName: publish deploy artifacts
          artifact: $(deploymentArtifacts)