extends: 
  - root.ruleset.yml
  - specification.ruleset.yml
  - authentication.ruleset.yml
  - errors.ruleset.yml
  - naming.ruleset.yml
  - request-response.ruleset.yml
  - serialization.ruleset.yml
  - url-structure.ruleset.yml 

rules:
  #  not keeping this, just off for testing in this repo
  oas3-unused-component: off